AWSTemplateFormatVersion: 2010-09-09
Description: ---

Parameters: 
  NameBase:
    Description: this is base name.
    Type: String
    Default:  RaiseTech

Resources: 
# s3バケット
  lecture13appbucket:
    Type: AWS::S3::Bucket
    Properties: 
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: lecture13-app-bucket
      VersioningConfiguration: 
        Status: Suspended
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-lecture13appbucket
# バケットポリシー
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref lecture13appbucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "s3:*"
            Resource:
              - "arn:aws:s3:::lecture13-app-bucket" 
              - "arn:aws:s3:::lecture13-app-bucket/*"
            Principal:
              AWS: !ImportValue EC2RoleArn

Outputs:
  lecture13appbucket:
    Description: The name of the S3 bucket
    Value: !Ref lecture13appbucket
    Export:
      Name: !Sub ${NameBase}-lecture13appbucket