---
- hosts: all
  remote_user: ec2-user  
  
  vars:
    ansible_become_method: sudo
    app_dir: /home/ec2-user/raisetech-live8-sample-app
    RDS_PASSWORD: "RDS_PASSWORD"
    EndpointAddress: "RDS_ENDPOINT"
    ALB_DNS: "DNS_NAME"
    S3_bucket_name: "S3_NAME"

  roles:
    - { role: 01_yum }
    - { role: 02_ruby }
    - { role: 03_node.js }
    - { role: 04_mysql }
    - { role: 05_deploy }