---
- hosts: all
  remote_user: ec2-user  

  vars:
    ansible_become_method: sudo
    app_dir: /home/ec2-user/raisetech-live8-sample-app
    MasterUserPassword: "{{ lookup('env', 'RDS_PASSWORD') }}"
    EndpointAddress: "{{ lookup('env', 'RDS_ENDPOINT') }}"
    ALB_DNS: "{{ lookup('env', 'DNS_NAME') }}"
    S3_bucket_name: "{{ lookup('env', 'S3_NAME') }}"

  roles:
    - { role: 01_yum }
    - { role: 02_ruby }
    - { role: 03_node.js }
    - { role: 04_mysql }
    - { role: 05_deploy }

  tasks:
    - name: Verify environment variables
      debug:
        msg:
          - "MasterUserPassword: {{ MasterUserPassword }}"
          - "EndpointAddress: {{ EndpointAddress }}"
          - "ALB_DNS: {{ ALB_DNS }}"
          - "S3_bucket_name: {{ S3_bucket_name }}"