require 'rake'
require 'rspec/core/rake_task'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  targets = []
  Dir.glob('./spec/*').each do |dir|
    next unless File.directory?(dir)
    target = File.basename(dir)
    target = "_#{target}" if target == "default"
    targets << target
  end

  task :all     => targets
  task :default => :all

  targets.each do |target|
    original_target = target == "_default" ? target[1..-1] : target
    desc "Run serverspec tests to #{original_target}"
    RSpec::Core::RakeTask.new(target.to_sym) do |t|
      # 固定IPアドレスを環境変数として指定
      ENV['TARGET_HOST'] = '52.197.254.56'

      # インベントリファイルを作成して、IPを指定
      File.open('inventory', 'w') do |file|
        file.puts "[myserver]"
        file.puts "myserver ansible_host=52.197.254.56 ansible_user=ec2-user"
      end

      t.pattern = "spec/#{original_target}/*_spec.rb"
    end
  end
end